In [5]:
import pandas as pd
import numpy as np

In [4]:
data=pd.read_csv("Stars.csv")
data

Temperature              L          R    A_M  Color Spectral_Class  Type
0           3068       0.002400     0.1700  16.12    Red              M     0
1           3042       0.000500     0.1542  16.60    Red              M     0
2           2600       0.000300     0.1020  18.70    Red              M     0
3           2800       0.000200     0.1600  16.65    Red              M     0
4           1939       0.000138     0.1030  20.06    Red              M     0
..           ...            ...        ...    ...    ...            ...   ...
235        38940  374830.000000  1356.0000  -9.93   Blue              O     5
236        30839  834042.000000  1194.0000 -10.63   Blue              O     5
237         8829  537493.000000  1423.0000 -10.73  White              A     5
238         9235  404940.000000  1112.0000 -11.23  White              A     5
239        37882  294903.000000  1783.0000  -7.80   Blue              O     5

[240 rows x 7 columns]

In [6]:
selectrandom=np.random.randint(0,240,size=10)
selectrandom

array([ 57, 103, 190, 223,  84, 126, 223,  98, 227, 169])

In [8]:
newTemp=data['Temperature'].copy()
newTemp[list(selectrandom)]=np.nan
data['newTemp']=newTemp
data

Temperature              L          R    A_M  Color Spectral_Class  Type  \
0           3068       0.002400     0.1700  16.12    Red              M     0   
1           3042       0.000500     0.1542  16.60    Red              M     0   
2           2600       0.000300     0.1020  18.70    Red              M     0   
3           2800       0.000200     0.1600  16.65    Red              M     0   
4           1939       0.000138     0.1030  20.06    Red              M     0   
..           ...            ...        ...    ...    ...            ...   ...   
235        38940  374830.000000  1356.0000  -9.93   Blue              O     5   
236        30839  834042.000000  1194.0000 -10.63   Blue              O     5   
237         8829  537493.000000  1423.0000 -10.73  White              A     5   
238         9235  404940.000000  1112.0000 -11.23  White              A     5   
239        37882  294903.000000  1783.0000  -7.80   Blue              O     5   

     newTemp  
0     3068.0  
1     3042.0  
2     2600.0  
3     2800.0  
4     1939.0  
..       ...  
235  38940.0  
236  30839.0  
237   8829.0  
238   9235.0  
239  37882.0  

[240 rows x 8 columns]

In [20]:
data2=data.loc[data['newTemp']==data['Temperature']]

In [21]:
data2

Temperature              L          R    A_M  Color Spectral_Class  Type  \
0           3068       0.002400     0.1700  16.12    Red              M     0   
1           3042       0.000500     0.1542  16.60    Red              M     0   
2           2600       0.000300     0.1020  18.70    Red              M     0   
3           2800       0.000200     0.1600  16.65    Red              M     0   
4           1939       0.000138     0.1030  20.06    Red              M     0   
..           ...            ...        ...    ...    ...            ...   ...   
235        38940  374830.000000  1356.0000  -9.93   Blue              O     5   
236        30839  834042.000000  1194.0000 -10.63   Blue              O     5   
237         8829  537493.000000  1423.0000 -10.73  White              A     5   
238         9235  404940.000000  1112.0000 -11.23  White              A     5   
239        37882  294903.000000  1783.0000  -7.80   Blue              O     5   

     newTemp  
0     3068.0  
1     3042.0  
2     2600.0  
3     2800.0  
4     1939.0  
..       ...  
235  38940.0  
236  30839.0  
237   8829.0  
238   9235.0  
239  37882.0  

[231 rows x 8 columns]

In [40]:
LR=data2[['L','R']]
np.array([np.array(LR['L']),np.array(LR['R'])])
arr=np.array([[x,y]for x,y in zip(np.array(LR['L']),np.array(LR['R']))])
arr

array([[2.40000e-03, 1.70000e-01],
       [5.00000e-04, 1.54200e-01],
       [3.00000e-04, 1.02000e-01],
       [2.00000e-04, 1.60000e-01],
       [1.38000e-04, 1.03000e-01],
       [6.50000e-04, 1.10000e-01],
       [7.30000e-04, 1.27000e-01],
       [4.00000e-04, 9.60000e-02],
       [6.90000e-04, 1.10000e-01],
       [1.80000e-04, 1.30000e-01],
       [2.90000e-03, 5.10000e-01],
       [1.22000e-02, 3.76100e-01],
       [4.00000e-04, 1.96000e-01],
       [5.50000e-03, 3.93000e-01],
       [6.00000e-04, 1.40000e-01],
       [3.80000e-03, 2.40000e-01],
       [1.80000e-03, 1.60000e-01],
       [3.67000e-03, 4.70000e-01],
       [3.62000e-03, 1.96700e-01],
       [3.90000e-02, 3.51000e-01],
       [5.60000e-02, 8.40000e-03],
       [4.90000e-04, 1.23400e-02],
       [1.70000e-04, 1.10000e-02],
       [5.00000e-04, 1.00000e-02],
       [1.30000e-02, 1.40000e-02],
       [8.50000e-05, 9.84000e-03],
       [8.10000e-04, 9.70000e-03],
       [1.10000e-04, 1.28000e-02],
       [1.50000e-04,

In [24]:
from sklearn.linear_model import LinearRegression

In [41]:
reg=LinearRegression().fit(arr,data2['newTemp'])

In [28]:
data4=data.loc[data['newTemp']!=data['Temperature']]
data4

Temperature             L          R     A_M       Color Spectral_Class  \
57          3450  174000.00000  1284.0000 -11.280         Red              M   
84         14100       0.00067     0.0089  12.170  Blue White              B   
98         12098     689.00000     7.0100   0.020  Blue-white              A   
103        17120  235000.00000    83.0000  -6.890        Blue              O   
126         2935       0.00087     0.0932  16.880         Red              M   
169         9373  424520.00000    24.0000  -5.990        Blue              O   
190         3462       0.00530     0.1480  11.470         Red              M   
223        23440  537430.00000    81.0000  -5.975        Blue              O   
227        10930  783930.00000    25.0000  -6.224        Blue              O   

     Type  newTemp  
57      5      NaN  
84      2      NaN  
98      3      NaN  
103     4      NaN  
126     0      NaN  
169     4      NaN  
190     1      NaN  
223     4      NaN  
227     4      NaN

In [43]:
reg.predict([np.array([174000.00000,1284.0000])])

array([8153.00180515])